# Generated by Django 3.2.7 on 2021-11-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Ordered Placed'), ('2', 'Shipping'), ('3', 'Delivered')], default=1, max_length=30),
        ),
    ]
