# Generated by Django 3.2.7 on 2021-11-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_prod_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
