# Generated by Django 3.2.7 on 2021-11-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[('1', 'Customer'), ('2', 'Seller')], default=1, max_length=30),
        ),
    ]
